name: Selenium UI Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  UI_TEST:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn clean package
    - name: Build the Docker image
      run: |
        cd ./deployment
        docker build  --tag automation-test-image .
#        docker volume create testVolume
    - name: Run UI Tests
      run: |
        mkdir ./deployment/test-output
        docker run --name uitest -v "$(pwd)"/deployment/test-output:/test-output automation-test-image
    - run: ls -lrt
    - run: ls ./deployment -lrt
    - run: ls ./deployment/test-output -lrt

    - name: Test Reports
      uses: actions/upload-artifact@v3
      with:
        name: htmlreports
        path: ./deployment/test-output