name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn clean package

    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file ./deployment/Dockerfile --tag automation-test-image
    - run: docker run automation-test-image